baseurl = "https://gogotattoo.github.io/gogo/"
languageCode = "en-us"
title = "ʕ•ᴥ•ʔ gogo.tattoo"
name = "gogo.tattoo"
copyright = "gogo.tattoo"
googleAnalytics = "UA-79234406-1"

[params]
# The path must be relative to the static folder
favicon = "favicon.ico"

[params.version]
  name = "0.0.3-alpha"
  code = 3

[taxonomies]
  tag = "tags"

[params.profile]
  avatar = "images/gogo.jpg"
  description = "I started working in the area of tattoos when I was 14, which is also when I made my first tattoo. So far I've had the chance to learn from masters in Singapore, Thailand, Phillipines, China, Russia, and other cool places throughout the world. Check out some of my previous works, and let me know if you want to start a cool new tattoo project with me."
  experience = "6+ years (since 2010)"
  location = "Shanghai"
  origin = "Shanghai"

  [params.profile.contact]
    chat = "contact.chat"
    email = "contact.email"
    wechat_qr = "contact.wechat_qr"
    line = "contact.line"
    steemit = "contact.steemit"
		headline = "contact.headline"
		description = "contact.description"
    # ... and so on...
    # TODO: maybe there's a better way to organize it?

# Navigation
[params.navigation]
  brand = "gogo@gogo.tattoo"

  [params.navigation.links]
    about     = "nav.about"
    services  = "nav.services"
    portfolio = "nav.portfolio"
    # Contact section
